"""empty message

Revision ID: 8fdcf1c3d831
Revises: 
Create Date: 2019-03-01 14:53:16.441935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fdcf1c3d831'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('os_drug_data',
    sa.Column('Appl_No', sa.Integer(), nullable=False),
    sa.Column('Product_No', sa.Integer(), nullable=True),
    sa.Column('Patent_No', sa.String(), nullable=True),
    sa.Column('Submission_Date', sa.DateTime(), nullable=True),
    sa.Column('Exclusivity_Code', sa.String(), nullable=True),
    sa.Column('Exclusivity_Date', sa.DateTime(), nullable=True),
    sa.Column('Trade_Name', sa.String(), nullable=True),
    sa.Column('Ingredient', sa.String(), nullable=True),
    sa.Column('Applicant', sa.String(), nullable=True),
    sa.Column('Approval_Date', sa.DateTime(), nullable=True),
    sa.Column('Type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Appl_No')
    )
    op.create_table('user',
    sa.Column('f_name', sa.String(length=20), nullable=False),
    sa.Column('l_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('company', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('os_drug_data')
    # ### end Alembic commands ###
